name: Validate Python projects
on:
  push:
jobs:
  find_projects:
    name: Generate matrix of project directories
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.set_output.outputs.matches }}
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: List directories
      run: find -name '*.py' -type 'f' -printf '%h\n' | uniq
    - name: Set output
      id: set_output
      run: echo "matches=$(find -name '*.py' -type 'f' -printf '%h\n' | uniq | jq --raw-input --compact-output --sort-keys '[., input?]')" >> $GITHUB_OUTPUT
  validate:
    name: Validate Python project
    needs: find_projects
    runs-on: ubuntu-latest
    container: python:3.7
    strategy:
      matrix:
        project-directory: ${{ fromJson(needs.find_projects.outputs.projects) }}
    defaults:
      run:
        working-directory: ${{ matrix.project-directory }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Output Python version
        run: python --version
      - name: Install packages
        run: pip install black flake8
      - name: Lint with flake8
        run: flake8 --count --verbose *.py
      - name: Check format with black
        run: black --check --verbose --line-length 79 *.py